logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
          support: DEBUG
        web: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:mem:vote
    username: user
    password: password
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create
        default_batch_fetch_size: 20
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 20
    show-sql: true
  cache:
    cache-names: users, restaurants, menus, votes
    caffeine:
      spec: expireAfterExcess=60s
  sql:
    init:
      mode: always
      platform: hsql
      data-locations: classpath:db/populateDB.sql
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc:
  paths-to-exclude: "/api/v1/votes/test"
