logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
          support: DEBUG
        web: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lunch_vote
    username: user
    password: password
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create
        default_batch_fetch_size: 20
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 20
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/populateDB.sql
server:
  port: 8080

